title: William Zhang
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Forge/FabricMC Modding, Competitive Programming, and Mobile Application Development
  <br><br>
  <a href="https://www.linkedin.com/in/william-zhang-968248212/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
