title: William Zhang
logo: "/images/logo.JPG?raw=true" # Logo image location (resource path).
description: > # Text/Descriptor Elements (<br> provides line breaks for multi-line descriptors).
  Mobile App Developer, Competitive Programmer, and Full-Stack Software Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/william-zhang-968248212/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
