import {
  escapeHtml as e,
  safeHref,
  dateLabel,
  template,
} from "./templates.mjs";
export function experienceRow(entry) {
  if (
    !entry.organization ||
    !entry.role ||
    !Array.isArray(entry.paragraphsHtml)
  )
    throw new Error(
      "Experience requires organization, role, and paragraphsHtml",
    );
  return `<article class="experience-row"><div class="experience-date">${e(entry.dates)}<span>${e(entry.category)}</span></div><div class="experience-content"><h3>${e(entry.organization)}</h3><p class="role">${e(entry.role)}</p>${entry.paragraphsHtml.map((html) => `<p>${html}</p>`).join("")}${entry.link ? `<a class="text-link" href="${safeHref(entry.link.href)}">${e(entry.link.label)} <span aria-hidden="true">↗</span></a>` : ""}${entry.details ? `<details class="experience-details"><summary>${e(entry.details.summary)}</summary><p>${entry.details.bodyHtml}</p></details>` : ""}</div></article>`;
}
export function projectCard(project) {
  if (!project.title || !Array.isArray(project.stack) || !project.link)
    throw new Error("Project requires title, stack, and link");
  return `<article class="project-card"><div class="project-top"><span class="eyebrow">${e(project.category)}</span><span class="project-year">${e(project.dates)}</span></div><h3>${e(project.title)}</h3><p>${e(project.description)}</p><p class="stack">${project.stack.map(e).join(" · ")}</p><a class="text-link" href="${safeHref(project.link.href)}">${e(project.link.label)} <span aria-hidden="true">↗</span></a></article>`;
}
export function postCard(post, index, prefix = "", level = 2) {
  return `<a class="writing-feature" href="${prefix}${post.slug}/"><div class="writing-meta"><span class="eyebrow">~/blog/${String(index + 1).padStart(3, "0")}</span><span>${dateLabel(post.date)}<br>${e(post.readMinutes)} min read</span></div><div><p class="eyebrow">${post.topics.map(e).join(" · ")}</p><h${level}>${e(post.title)}</h${level}><p>${e(post.description)}</p><span class="text-link">Read article <span aria-hidden="true">↗</span></span></div></a>`;
}
export function page(
  root,
  site,
  {
    title,
    description,
    prefix = "",
    blog = false,
    article = false,
    tools = false,
    pageClass = "",
    modulePath = blog || tools ? null : "assets/js/site.js",
    body,
  },
) {
  const header = template(root, "partials/header", {
    homeHref: prefix || "#",
    prefix,
    blogCurrent: blog ? 'aria-current="page"' : "",
    toolsCurrent: tools ? 'aria-current="page"' : "",
    resumePath: e(site.resumePath),
  });
  const footer = template(root, "partials/footer", {
    year: e(site.year),
    name: e(site.name),
    footerMiddle:
      blog && !article
        ? `<a href="mailto:${e(site.email)}">Contact ↗</a>`
        : '<a href="#">Back to top ↑</a>',
    footerLink:
      blog || tools
        ? `<a href="${prefix}">Portfolio ↗</a>`
        : "<span>Portfolio / " + e(site.year) + "</span>",
  });
  return `<!doctype html>\n<!-- Generated by npm run generate. Edit content/ and src/templates/. -->\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="theme-color" content="#f4f4f1"><title>${e(title)}</title><meta name="description" content="${e(description)}">${article ? `<meta property="og:type" content="article"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}">` : ""}<link rel="icon" href="${prefix}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}assets/css/site.css"><link rel="stylesheet" href="${prefix}assets/css/boot.css"><script src="${prefix}assets/js/boot.js"></script>${modulePath ? `<script type="module" src="${safeHref(prefix + modulePath)}"></script>` : ""}</head><body${pageClass ? ` class="${e(pageClass)}"` : ""}><a class="skip-link" href="#main">Skip to content</a>${header}<main id="main" class="page-width">${body}</main>${footer}</body></html>\n`;
}
