import { readFileSync } from "node:fs";
import { join } from "node:path";
export const styleOrder = [
  "base",
  "portfolio",
  "article",
  "theme",
  "responsive",
  "logic-board",
  "tools",
];
export function compileStyles(root) {
  return (
    "/* Generated by npm run generate. Edit assets/css/modules/. */\n" +
    styleOrder
      .map(
        (name) =>
          `/* ${name} */\n${readFileSync(join(root, "assets/css/modules", `${name}.css`), "utf8")}`,
      )
      .join("\n")
  );
}
